version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      aws:
        patterns: ['aws-cdk*', '@aws-sdk/*', 'cdk-nag', 'constructs']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
