// Generates src/backend/seed/pages.generated.ts from src/backend/seed/*.md (default wiki pages).
//   node scripts/gen-seed.mjs          write the file
//   node scripts/gen-seed.mjs --check  exit 1 if the committed file is out of date (used by lint)
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = new URL('../src/backend/seed/', import.meta.url).pathname;
const pages = readdirSync(dir)
  .filter((f) => f.endsWith('.md'))
  .sort()
  .map((f) => ({ id: f.slice(0, -3), text: readFileSync(join(dir, f), 'utf8') }));
const out =
  '// GENERATED by scripts/gen-seed.mjs from src/backend/seed/*.md — do not edit by hand.\n' +
  '/** Default wiki pages (OKF documents) created once when missing. */\n' +
  `export const SEED_PAGES: { id: string; text: string }[] = ${JSON.stringify(pages, null, 2)};\n`;
const target = join(dir, 'pages.generated.ts');
if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(target, 'utf8');
  } catch {
    /* missing */
  }
  if (current !== out) {
    console.error('gen-seed: src/backend/seed/pages.generated.ts is out of date; run: node scripts/gen-seed.mjs');
    process.exit(1);
  }
} else {
  writeFileSync(target, out);
  console.log(`gen-seed: ${pages.length} page(s) -> ${target}`);
}
